version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install

  pre_build:
    commands:
      # Add any pre-build commands here, like linting or tests

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
